spring:
  application:
    name: generate-provider
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    logSlowSql: true
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${DB_HOST:localhost}:3306/store?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    validationQuery: SELECT 1 FROM DUAL

http:
  connection:
     keepAliveTimeout: 60000


zlt:
  swagger-agg:
    generate-routes: user,file
  oauth2:
    token:
      store:
        type: redis

